# Generated by Django 6.0.1 on 2026-01-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationdetails',
            name='purpose',
        ),
    ]
