# Generated by Django 6.0.1 on 2026-01-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_remove_contactmessage_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='short_description',
        ),
    ]
